Iter5
blagorodov/go-shortener pull request #4
Opened 2023-09-14 21:13 UTC by blagorodov

Iteration 5: added .env

2023-09-15 15:49 UTC, gonozov0 requested changes
Отличная работа! Есть пара замечаний, которые необходимо устранить для того, чтобы код стал более чистым, расширяемым и легче воспринимаемым. Очень понравилось, насколько качественно разделил сервер, хендлеры и старт приложения, респект!

2023-09-15 15:49 UTC, gonozov0 commented on internal/app/config/config.go
> +	testing.Init()
Подскажи плиз, зачем инициализировать тестовые енвы?

2023-09-15 15:49 UTC, gonozov0 commented on internal/app/config/config.go
> +var Options = new(Config)
new не особо принято в для экземпляров структур юзать, лучше Config{}

2023-09-15 15:49 UTC, gonozov0 commented on internal/app/config/config.go
> +func init() {
init также не принято широко использовать.
Я бы предпочел, вместо использования глобальной переменной и ее инициализации через init, лучше создать отдельную функцию LoadConfig, которая будет возвращать инициализированный Config. Такую реализацию проще было бы воспринимать и читать.
Но не наставиваю, такой вариант тоже рабочий

2023-09-15 15:49 UTC, gonozov0 commented on internal/app/repositories/repositories.go
> +type LinksRepository interface {
Выглядит странно, что интерфейс называется LinksRepository в пакете repository, а его имплементация через использование оперативной памяти Links в пакете storage, как будто это не связанные вещи.

Есть 2 принятых варианта складирования интерфейсов по чистой архитектуре на моей опыте:
1. объявить в том же пакете неэкспортируемым (с прописной буквы), где этот интерфейс используется (т.е. в нашем случае в пакете handlers в файле, к примеру, storage.go)
2. объявить в том же пакете, где и располагается реализация интерфейсов (т.е. в storage пакете в файл interface.go)

Я сам обычно делаю по второму второму варианту.
Также важно, чтобы названия интерфейсов и реализаций были в одном стиле, например? интерфейс Repository и реализация InMemoryRepository, или Storage и InMemoryStorage

2023-09-15 15:49 UTC, gonozov0 commented on internal/app/storage/storage.go
> +}
Здесь точно нельзя делать глобальную мапу, это в дальнейшем может привезти, как к неожиданным последствиям, если проект разрастется и много где будет она использоваться. Также это потенциальная утечка помяти, т.к. для сборщика мусора на этот объект всегда будет ссылка и освобождения памяти по ходу программы не будет.

Вообще старайся нигде не использовать глобальные объекты - это серьезный антипаттерн

Сделай Links (или то как это будет называться после рефакторга интерфейса) структурой, в которой будет уже мапа
Вместо init нам нужен полноценный конструктор, который будет возвращать эту структуру, любой конструктор в GO принято начинать называть "New" + название структуры

2023-09-15 15:49 UTC, gonozov0 commented on internal/app/utils/utils.go
> +package utils
старайся не создавать таких пакетов, а также аналогов по типу "common" и прочее. В больших проектах и реальной разаработке такие пакеты и файлы превращаются в настоящую свалку из кода, которую потом очень тяжело и болезненно сортировать.

В твоем случае все добавляемые функции используются лишь по одному разу, давай их туда, где они используются и положим, сделав их вдобавок неэкспортируемыми

2023-09-15 15:49 UTC, gonozov0 commented on internal/app/server/server.go
> +func Router() *chi.Mux {
используется только в этом файле, лучше сделать тогда неэкспортируемым

2023-09-16 18:49 UTC, blagorodov commented on internal/app/config/config.go
> +	testing.Init()
Без их инициализации при запуске моего теста server_test.go выдается такая ошибка:
![image](https://github.com/blagorodov/go-shortener/assets/50463525/55681d8d-aa97-4e41-9dcd-02e19c5811a6)

То есть он ждет эти тестовые флаги, которые не имеют дефолтов, я так понимаю. 
Я понимаю, что это какой-то костыль. Как лучше тут поступить?

2023-09-16 19:18 UTC, blagorodov commented on internal/app/config/config.go
> +func init() {
Попробовал вообще убрать глобальный Options, но в этом случае мне нужно при каждом использовании вызывать LoadConfig() - таких вызовов получается несколько и он ругается, что флаг уже определен. Как поступить?

2023-09-16 19:42 UTC, blagorodov commented on internal/app/repositories/repositories.go
> +type LinksRepository interface {
Поправил, но не могу пока понять, зачем вообще здесь нужен этот интерфейс, если мы его используем только внутри пакета storage.

2023-09-16 20:00 UTC, blagorodov commented on internal/app/storage/storage.go
> +}
А как обойтись без глобального хранилища тогда?

2023-09-16 20:10 UTC, blagorodov commented on internal/app/server/server.go
> +func Router() *chi.Mux {
Router() также используется в server_test.go. Как быть?

2023-09-17 17:36 UTC, gonozov0 commented on internal/app/config/config.go
> +	testing.Init()
Странно, не сталкивался, может какие-то библиотеки лишние тянут за собой исопльзование этого флага? У тебя go-spew и go-difflib вроде не используются

2023-09-17 17:37 UTC, gonozov0 commented on internal/app/server/server.go
> +func Router() *chi.Mux {
код server_test.go находится в том же package, все неэкспортируемые функции должны быть там доступны

2023-09-17 17:41 UTC, gonozov0 commented on internal/app/config/config.go
> +func init() {
А, ну да, парсить флаги по несколько раз неполучится, как считывать енвы, окей, давай оставим твой текущий вариант с глобальным конфигом

2023-09-17 17:46 UTC, gonozov0 commented on internal/app/repositories/repositories.go
> +type LinksRepository interface {
В том то и дело, что мы должны аперировать интерфейсами в хендлерах. У тебя хендлер должен использовать именно интерфейс в своем коде, а передавать реальную реализацию этого интерфейса мы должны в твоей случае в функции `router`

2023-09-17 17:48 UTC, gonozov0 commented on internal/app/storage/storage.go
> +}
в `router` вызываешь `storage := NewInMemoryStorage()` и передаешь его при инициализации структуры хендлера или как аргумент функции хендлера

2023-09-17 17:50 UTC, gonozov0 requested changes
Интерфейс реализован, но не используется, как необходимо. Давай откажемся от глобальных объектов, будем создавать нужный нам storage в функции router, а в коде хендлеров оперировать интерфейсом

2023-09-18 05:44 UTC, blagorodov commented on internal/app/config/config.go
> +	testing.Init()
Я так понимаю, что это известная проблема. Нашел вот такое:
https://github.com/golang/go/issues/31859#issuecomment-489889428

2023-09-18 06:42 UTC, blagorodov commented on internal/app/storage/storage.go
> +}
Я подумал, что правильнее определять конкретную реализацию стораджа на уровне запуске программы, в main()

2023-09-18 07:41 UTC, gonozov0 approved these changes
Супер, все критичные моменты поправлены

2023-09-18 07:46 UTC, merged